pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        withPythonEnv('python') {
          sh 'python --version'
          sh 'sudo pip install virtualenv'
          sh 'pip install -U pytest'
        }
      }
    }
    stage('test') {
      steps {
        sh 'pytest'
      }   
    }
  }
}